FROM python:3.11-slim

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir pandas numpy scikit-learn joblib fastapi uvicorn

EXPOSE 8000

CMD ["uvicorn", "stage6_inference_api:app", "--host", "0.0.0.0", "--port", "8000", "--app-dir", "06-inference-api"]
